apiVersion: v1
kind: ConfigMap
metadata:
  name: mem-cpu-trending-script-slow
  labels:
    app.kubernetes.io/name: {{ include "mem-cpu-trending-slow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  mem-cpu-trending.go: |-
{{- .Values.mem_cpu_trending_script | nindent 4 }}
